### ISSUE TITLE
Unable to create app in mac

### ISSUE THREAD

**Issue by kaustubhai** [Vector26/create-express-mvt#1]
## Getting this error: 
![image](https://user-images.githubusercontent.com/47121025/137146739-f73971b6-cf1f-4a03-b863-113cd295fd18.png)

**Comment by Vector26** [comment]
Fixed the bug
Changed all instances of "\\\\" to "/". 
## From
![image](https://user-images.githubusercontent.com/23053807/137157167-e1f02ec4-0de2-40a2-accf-c888f2ec8460.png)
## To
![image](https://user-images.githubusercontent.com/23053807/137157101-33791ec8-4a69-46d9-b49b-f6bda4a2ca65.png)

Tested it out on debian linux as well
